####################################################
# UILOVELACE - OTHERS                              #
####################################################

- title: Tests
  icon: mdi:car-connected
  # Unique path for direct access /lovelace/${path}
  path: cars
  visible: true
  badges:
    - sensor.time
  cards:
    - type: picture-elements
      title: Lexus Start
      #icon: 'mdi:car-connected'
      image: /local/images/Remotes/Orbit2350_Remote5.png
      elements:
        - type: image
          entity: input_boolean.cars_lexus_lock
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 55%
            top: 28%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_lexus_lock
        - type: image
          entity: input_boolean.cars_lexus_unlock
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 55%
            top: 42%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_lexus_unlock
        - type: image
          entity: input_boolean.cars_lexus_other1
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 55%
            top: 57%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_lexus_other1
        - type: image
          entity: input_boolean.cars_lexus_start
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 55%
            top: 72%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_lexus_start

    - type: picture-elements
      title: Journey Start  
      #icon: 'mdi:car-connected'
      image: /local/images/Remotes/DodgeJourneyRemote3.png
      elements:
        - type: image
          entity: input_boolean.cars_journey_lock
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 54%
            top: 18%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_journey_lock
        - type: image
          entity: input_boolean.cars_journey_unlock
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 43%
            top: 15%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_journey_unlock
        - type: image
          entity: input_boolean.cars_journey_start
          state_image:
            "on": /local/images/Remotes/Orbit2350ButtonOn.png
            "off": /local/images/Remotes/Orbit2350ButtonOff.png
          style:
            left: 54%
            top: 39%
            width: 15%
            height: 15%
          tap_action:
            action: call-service
            service: input_boolean.turn_on
            service_data:
              entity_id: input_boolean.cars_journey_start
              