####################################################
# TIME COUNTER                                     #
####################################################

  # my_counter:
    # name: string
    # duration: int, required [s]
    # initial: int, defaults to 0
    # min: int, defaults to 0
    # max: int, defaults to 100
    # debounce: int, optional, defaults to 1000 [ms]
    
    #You can also set icon and restore as documented in counter component.
    
