##########################################
# CUSTOMIZATIONS - LIGHTS                #
##########################################
  
# STANDARD COLORS
#=========================================
# Icon Online:  var(--state-icon-color) --> #007AFF
# Icon Offline: var(--state-icon-unavailable-color) --> #4F5F78
# Icon Active:  var(--state-icon-active-color) --> #FBCD41
# Red:          FF0000
# Yellow:       FFFF00
# Orange:       FFA500
# Lt Purple:    A500FF
# Dk Purple:    5C005C
# Lt Green:     00FF00
# Gold:         A3852A

  light.pool_clock:
    icon: mdi:clock